repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-case-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: debug-statements

  - repo: local
    hooks:
      - id: check
        name: check
        entry: bash -c 'make check'
        language: system
        require_serial: true
