# Generated by Django 4.1.7 on 2023-04-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                default="icons/avatar.svg", null=True, upload_to=""
            ),
        ),
    ]
