# Generated by Django 4.1.7 on 2023-04-24 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0002_alter_room_host"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("replies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="replies",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="rooms.room",
            ),
        ),
        migrations.AlterField(
            model_name="replies",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
