# Generated by Django 4.1.7 on 2023-04-25 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rooms", "0001_initial"),
        ("replies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="replies",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="rooms.room",
            ),
        ),
    ]
