# Generated by Django 4.1.7 on 2023-04-29 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("replies", "0003_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="replies",
            options={
                "ordering": ["-updated", "-created"],
                "verbose_name": "Replies",
                "verbose_name_plural": "Replies",
            },
        ),
    ]
