# Generated by Django 4.1.7 on 2023-12-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("replies", "0004_alter_replies_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="replies",
            name="accepted",
            field=models.BooleanField(default=False),
        ),
    ]
